version: '3.9'
services:

  #######################################################
  #  Elastic Search to store logs
  #######################################################
  elasticsearch:
    container_name: elasticsearch
    image: 'elasticsearch:8.3.3'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic
    labels:
      - co.elastic.logs/module=elasticsearch
      - co.elastic.metrics/module=elasticsearch

  #######################################################
  #  Kibana to browse logs
  #######################################################
  kibana:
    image: 'kibana:8.3.3'
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic
  
  #######################################################
  #  Logstash
  #######################################################
  logstash:
    image: 'logstash:8.3.3'
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elastic
    volumes:
      - './conf/logstash.conf:/etc/logstash/conf.d/logstash.conf'
      - './conf/patterns:/opt/logstash/patterns'
    ports:
      - target: 5044
        published: 5044
  
  #######################################################
  #  Filebeat
  #######################################################
  filebeat:
    user: root
    image: 'docker.elastic.co/beats/filebeat:8.3.3'
    container_name: filebeat
    command: filebeat -e --strict.perms=false
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - './conf/filebeat.yml:/usr/share/filebeat/filebeat.yml'
      - 'logs_data:/logs'
    networks:
      - elastic
    depends_on:
      - logstash
  
  elk-stack:
    container_name: ms-service-1
    build: ./elk-stack
    volumes:
      - 'logs_data:/logs'
    ports:
      - '8081:8081'
  
  elk-vendor:
    container_name: ms-service-2
    build: ./elk-vendor
    volumes:
      - 'logs_data:/logs'
    ports:
      - '8082:8082'
    
volumes:
  es_data:
    driver: local
  logs_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
